modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Kyagara/CoopTweaks/issues"
license = "Apache-2.0"

[[mods]]
modId = "cooptweaks"
version = "${version}"
displayName = "CoopTweaks"
authors = "Kyagara"
description = '''
Sync advancements, chat relay for Discord and more.
'''
#logoFile = ""

[[dependencies.cooptweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cooptweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cooptweaks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cooptweaks.mixins.json"
