name: build

on:
  push:
    branches:
      - "**"
    paths:
      - "gradle/wrapper/**"
      - ".github/workflows/build.yaml"
      - "**.java"
      - "**.json"
      - "*.gradle"
      - "gradle.properties"

env:
  VERSIONS: ("1.21.1")

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew chiseledBuildAndCollect

      - name: Move jars
        run: |
          for version in ${{ env.VERSIONS }}; do
            mv ./versions/*/build/libs/*fabric.jar ./versions/*/build/libs/*neoforge.jar ./build/$version/
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            ./build
